### ISSUE TITLE
Update to v1.5

### ISSUE THREAD

**Issue by sudar** [sudar/homebrew-arduino-mk#3]
@ladislas I just released v1.5 of the makefile and I was trying to update the formula

```
homepage 'https://github.com/sudar/Arduino-Makefile'
    url 'https://github.com/sudar/Arduino-Makefile/archive/1.3.4.tar.gz'
    sha256 '66311654a0fceda7bcfcba3de570040ec13e58619a6200da3ac6240b569195e2'
```

In the above code is the sha256 the checksum of the achieve file or the sha of the commit?

**Comment by ladislas** [comment]
It's the sha of the archive file. :)
